// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/course/": {
            "get": {
                "description": "Get all courses that follows a criteria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course request"
                ],
                "summary": "Get all courses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Title string for which you want to look",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ownerEmail string for which you want to look",
                        "name": "ownerEmail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "category string for which you want to look",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Age of the course you want to retrieve",
                        "name": "desiredAge",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "true if school oriented, any other value otherwise",
                        "name": "isSchoolOriented",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CourseStateResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            },
            "post": {
                "description": "Create course using the token as a way to add account to course owner",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course request"
                ],
                "summary": "Create course",
                "parameters": [
                    {
                        "description": "Title and Category are required",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CourseRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token required for request",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CourseState"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/course/subscribe/": {
            "get": {
                "description": "Get all courses in which the user has subscribed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Get subscribed courses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token required for request",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CourseStateResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/course/subscribe/{id}": {
            "post": {
                "description": "Subscribe a user given by its token to a course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Subscribe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "course in which the current user wants to subscribe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token required for request",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "Object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/course/{id}": {
            "get": {
                "description": "Fetch a course with a given id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course request"
                ],
                "summary": "Fetch a course",
                "parameters": [
                    {
                        "type": "string",
                        "description": "course id which you look for",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token required for request",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CourseState"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            },
            "post": {
                "description": "Create class for a previously created course, if course does not exist this endpoint will fail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course request"
                ],
                "summary": "Create class for created course",
                "parameters": [
                    {
                        "description": "Title is required",
                        "name": "class",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.Class"
                        }
                    },
                    {
                        "type": "string",
                        "description": "course id which you want to add a course",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CourseState"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/course/{id}/{classId}": {
            "get": {
                "description": "Get class with id and class id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course request"
                ],
                "summary": "Fetch a class",
                "parameters": [
                    {
                        "type": "string",
                        "description": "class id you want to fetch",
                        "name": "classId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "course id which you look for",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Class"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes a class",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course request"
                ],
                "summary": "Remove class created",
                "parameters": [
                    {
                        "type": "string",
                        "description": "class id you want to remove",
                        "name": "classId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "course id which you look for",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/exams/submission": {
            "post": {
                "description": "Given a user identified by its token, submit a resolution",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams request"
                ],
                "summary": "Add submission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token required for request",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "At least one point is required",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.Submission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Score"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/exams/{courseId}/{classId}": {
            "get": {
                "description": "Given a course id and a class id, gets the specific exam",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams request"
                ],
                "summary": "Get an exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "class id you want to remove",
                        "name": "classId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "course id which you look for",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Exam"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            },
            "post": {
                "description": "Given a course id and a class id, creates an exam for the class",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams request"
                ],
                "summary": "Create an exam for a given class",
                "parameters": [
                    {
                        "description": "At least one point is required",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CreateExamRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "class id you want to remove",
                        "name": "classId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "course id which you look for",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes an exam already created",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams request"
                ],
                "summary": "Remove exam created",
                "parameters": [
                    {
                        "type": "string",
                        "description": "class id you want to remove",
                        "name": "classId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "course id which you look for",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/scores/{courseId}/class/{classId}": {
            "get": {
                "description": "Given a course id and a class id and a user, gets the specific score",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams request"
                ],
                "summary": "Get a score",
                "parameters": [
                    {
                        "type": "string",
                        "description": "class id you want to look for",
                        "name": "classId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "course id which you look for",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token required for request",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Score"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/scores/{courseId}/class/{classId}/{userEmail}": {
            "get": {
                "description": "Given a course id and a class id and a user, gets the specific score",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams request"
                ],
                "summary": "Get a score",
                "parameters": [
                    {
                        "type": "string",
                        "description": "class id you want to look for",
                        "name": "classId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "course id which you look for",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "email you look for, is an exact match",
                        "name": "userEmail",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Score"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/scores/{courseId}/user/{userEmail}": {
            "get": {
                "description": "Given a course id and a user email, gets all the scores from that user in given course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams request"
                ],
                "summary": "Get an exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "course id which you look for",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "email you look for, is an exact match",
                        "name": "userEmail",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.Score"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/user/login/": {
            "post": {
                "description": "SignInUser",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User request"
                ],
                "summary": "SignIn User",
                "parameters": [
                    {
                        "description": "Email and Password are required",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Token"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "get": {
                "description": "Get User profile with token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User request"
                ],
                "summary": "Get User Profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token required for request",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/user/profile/{id}": {
            "get": {
                "description": "Get User Profile",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User request"
                ],
                "summary": "Get User Profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update User Profile",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User request"
                ],
                "summary": "Update User Profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Profile and Name are updatable",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/user/signUp/": {
            "post": {
                "description": "Create User Account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User request"
                ],
                "summary": "Sign Up User",
                "parameters": [
                    {
                        "description": "User required Data to SignUp",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Token"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.Class": {
            "type": "object",
            "properties": {
                "course_title": {
                    "type": "string"
                },
                "metadata": {},
                "title": {
                    "type": "string"
                }
            }
        },
        "controller.CourseRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "classes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.Class"
                    }
                },
                "is_school_oriented": {
                    "type": "boolean"
                },
                "max_age": {
                    "type": "integer"
                },
                "metadata": {},
                "min_age": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "controller.CourseState": {
            "type": "object",
            "properties": {
                "age_filtered": {
                    "type": "boolean"
                },
                "category": {
                    "type": "string"
                },
                "classes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "courseTitle": {
                    "type": "string"
                },
                "creatorEmail": {
                    "type": "string"
                },
                "isSchoolOriented": {
                    "type": "boolean"
                },
                "isSubscribed": {
                    "type": "boolean"
                },
                "max_age": {
                    "type": "integer"
                },
                "metadata": {},
                "min_age": {
                    "type": "integer"
                }
            }
        },
        "controller.CourseStateResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.CourseState"
                    }
                }
            }
        },
        "controller.CreateExamRequest": {
            "type": "object",
            "required": [
                "points"
            ],
            "properties": {
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.Point"
                    }
                }
            }
        },
        "controller.ErrorMsg": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string",
                    "example": "mensaje de error"
                }
            }
        },
        "controller.Exam": {
            "type": "object",
            "properties": {
                "class": {
                    "type": "string"
                },
                "course": {
                    "type": "string"
                },
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.Point"
                    }
                }
            }
        },
        "controller.Point": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "possibilities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "question": {
                    "type": "string"
                }
            }
        },
        "controller.Score": {
            "type": "object",
            "properties": {
                "correct_amount": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "integer"
                }
            }
        },
        "controller.Submission": {
            "type": "object",
            "required": [
                "class",
                "course",
                "points"
            ],
            "properties": {
                "class": {
                    "type": "string"
                },
                "course": {
                    "type": "string"
                },
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.SubmissionPoint"
                    }
                }
            }
        },
        "controller.SubmissionPoint": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                }
            }
        },
        "controller.Token": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "asdasfasd"
                }
            }
        },
        "controller.UserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "metadata": {},
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "profile": {
                    "type": "string"
                }
            }
        },
        "controller.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "metadata": {},
                "name": {
                    "type": "string"
                },
                "profile": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
