definitions:
  controller.ErrorMsg:
    properties:
      reason:
        example: mensaje de error
        type: string
    type: object
  controller.Token:
    properties:
      token:
        example: asdasfasd
        type: string
    type: object
  controller.UserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      profile:
        type: string
    type: object
  controller.UserResponse:
    properties:
      email:
        type: string
      name:
        type: string
      profile:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/login/:
    post:
      consumes:
      - application/json
      description: SignInUser
      parameters:
      - description: Email and Password are required
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: SignIn User
      tags:
      - login
  /user/profile/{id}:
    get:
      description: Get User Profile
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: Get User Profile
      tags:
      - getUser
    patch:
      description: Update User Profile
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Profile and Name are updatable
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: Update User Profile
      tags:
      - updateUser
  /user/signUp/:
    post:
      consumes:
      - application/json
      description: Create User Account
      parameters:
      - description: User required Data to SignUp
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: Sign Up User
      tags:
      - signup
swagger: "2.0"
