definitions:
  controller.Class:
    properties:
      course_title:
        type: string
      metadata: {}
      title:
        type: string
    type: object
  controller.CourseRequest:
    properties:
      category:
        type: string
      classes:
        items:
          $ref: '#/definitions/controller.Class'
        type: array
      max_age:
        type: integer
      metadata: {}
      min_age:
        type: integer
      title:
        type: string
    type: object
  controller.CourseState:
    properties:
      age_filtered:
        type: boolean
      category:
        type: string
      classes:
        items:
          type: string
        type: array
      courseTitle:
        type: string
      creatorEmail:
        type: string
      max_age:
        type: integer
      metadata: {}
      min_age:
        type: integer
    type: object
  controller.ErrorMsg:
    properties:
      reason:
        example: mensaje de error
        type: string
    type: object
  controller.Token:
    properties:
      token:
        example: asdasfasd
        type: string
    type: object
  controller.UserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      profile:
        type: string
    type: object
  controller.UserResponse:
    properties:
      email:
        type: string
      name:
        type: string
      profile:
        type: string
    type: object
info:
  contact: {}
paths:
  /course/:
    get:
      consumes:
      - application/json
      description: Get all courses that follows a criteria
      parameters:
      - description: Title string for which you want to look
        in: query
        name: title
        type: string
      - description: ownerEmail string for which you want to look
        in: query
        name: ownerEmail
        type: string
      - description: category string for which you want to look
        in: query
        name: category
        type: string
      - description: Age of the course you want to retrieve
        in: query
        name: desiredAge
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controller.CourseState'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: Get all courses
      tags:
      - Course request
    post:
      consumes:
      - application/json
      description: Create course using the token as a way to add account to course
        owner
      parameters:
      - description: Title and Category are required
        in: body
        name: course
        required: true
        schema:
          $ref: '#/definitions/controller.CourseRequest'
      - description: token required for request
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CourseState'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: Create course
      tags:
      - Course request
  /course/{id}:
    get:
      consumes:
      - application/json
      description: Fetch a course with a given id
      parameters:
      - description: course id which you look for
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CourseState'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: Fetch a course
      tags:
      - Course request
    post:
      consumes:
      - application/json
      description: Create class for a previously created course, if course does not
        exist this endpoint will fail
      parameters:
      - description: Title is required
        in: body
        name: class
        required: true
        schema:
          $ref: '#/definitions/controller.Class'
      - description: course id which you want to add a course
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CourseState'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: Create class for created course
      tags:
      - Course request
  /course/{id}/{classId}:
    delete:
      consumes:
      - application/json
      description: Removes a class
      parameters:
      - description: class id you want to remove
        in: path
        name: classId
        required: true
        type: string
      - description: course id which you look for
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: Remove class created
      tags:
      - Course request
    get:
      consumes:
      - application/json
      description: Get class with id and class id
      parameters:
      - description: class id you want to fetch
        in: path
        name: classId
        required: true
        type: string
      - description: course id which you look for
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Class'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: Fetch a class
      tags:
      - Course request
  /user/login/:
    post:
      consumes:
      - application/json
      description: SignInUser
      parameters:
      - description: Email and Password are required
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: SignIn User
      tags:
      - User request
  /user/profile/{id}:
    get:
      description: Get User Profile
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: Get User Profile
      tags:
      - User request
    patch:
      description: Update User Profile
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Profile and Name are updatable
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: Update User Profile
      tags:
      - User request
  /user/signUp/:
    post:
      consumes:
      - application/json
      description: Create User Account
      parameters:
      - description: User required Data to SignUp
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorMsg'
      summary: Sign Up User
      tags:
      - User request
swagger: "2.0"
